/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
	"time"
)

// Applicant struct for Applicant
type Applicant struct {
	// The unique identifier for the applicant. Read-only.
	Id *string `json:"id,omitempty"`
	// The date and time when this applicant was created. Read-only.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The date and time when this applicant is scheduled to be deleted. Read-only.
	DeleteAt *time.Time `json:"delete_at,omitempty"`
	// The uri of this resource. Read-only.
	Href *string `json:"href,omitempty"`
	// Read-only.
	Sandbox *bool `json:"sandbox,omitempty"`
	// The applicant’s first name
	FirstName *string `json:"first_name,omitempty"`
	// The applicant’s surname
	LastName *string `json:"last_name,omitempty"`
	// The applicant’s email address. Required if doing a US check, or a UK check for which `applicant_provides_data` is `true`.
	Email *string `json:"email,omitempty"`
	// The applicant’s date of birth
	Dob *string `json:"dob,omitempty"`
	Address *Address `json:"address,omitempty"`
	IdNumbers *[]IdNumber `json:"id_numbers,omitempty"`
	Location *Location `json:"location,omitempty"`
}

// NewApplicant instantiates a new Applicant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicant() *Applicant {
	this := Applicant{}
	return &this
}

// NewApplicantWithDefaults instantiates a new Applicant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicantWithDefaults() *Applicant {
	this := Applicant{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Applicant) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Applicant) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Applicant) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Applicant) SetId(v string) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Applicant) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Applicant) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Applicant) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Applicant) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetDeleteAt returns the DeleteAt field value if set, zero value otherwise.
func (o *Applicant) GetDeleteAt() time.Time {
	if o == nil || o.DeleteAt == nil {
		var ret time.Time
		return ret
	}
	return *o.DeleteAt
}

// GetDeleteAtOk returns a tuple with the DeleteAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Applicant) GetDeleteAtOk() (*time.Time, bool) {
	if o == nil || o.DeleteAt == nil {
		return nil, false
	}
	return o.DeleteAt, true
}

// HasDeleteAt returns a boolean if a field has been set.
func (o *Applicant) HasDeleteAt() bool {
	if o != nil && o.DeleteAt != nil {
		return true
	}

	return false
}

// SetDeleteAt gets a reference to the given time.Time and assigns it to the DeleteAt field.
func (o *Applicant) SetDeleteAt(v time.Time) {
	o.DeleteAt = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *Applicant) GetHref() string {
	if o == nil || o.Href == nil {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Applicant) GetHrefOk() (*string, bool) {
	if o == nil || o.Href == nil {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *Applicant) HasHref() bool {
	if o != nil && o.Href != nil {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *Applicant) SetHref(v string) {
	o.Href = &v
}

// GetSandbox returns the Sandbox field value if set, zero value otherwise.
func (o *Applicant) GetSandbox() bool {
	if o == nil || o.Sandbox == nil {
		var ret bool
		return ret
	}
	return *o.Sandbox
}

// GetSandboxOk returns a tuple with the Sandbox field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Applicant) GetSandboxOk() (*bool, bool) {
	if o == nil || o.Sandbox == nil {
		return nil, false
	}
	return o.Sandbox, true
}

// HasSandbox returns a boolean if a field has been set.
func (o *Applicant) HasSandbox() bool {
	if o != nil && o.Sandbox != nil {
		return true
	}

	return false
}

// SetSandbox gets a reference to the given bool and assigns it to the Sandbox field.
func (o *Applicant) SetSandbox(v bool) {
	o.Sandbox = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *Applicant) GetFirstName() string {
	if o == nil || o.FirstName == nil {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Applicant) GetFirstNameOk() (*string, bool) {
	if o == nil || o.FirstName == nil {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *Applicant) HasFirstName() bool {
	if o != nil && o.FirstName != nil {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *Applicant) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *Applicant) GetLastName() string {
	if o == nil || o.LastName == nil {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Applicant) GetLastNameOk() (*string, bool) {
	if o == nil || o.LastName == nil {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *Applicant) HasLastName() bool {
	if o != nil && o.LastName != nil {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *Applicant) SetLastName(v string) {
	o.LastName = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *Applicant) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Applicant) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *Applicant) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *Applicant) SetEmail(v string) {
	o.Email = &v
}

// GetDob returns the Dob field value if set, zero value otherwise.
func (o *Applicant) GetDob() string {
	if o == nil || o.Dob == nil {
		var ret string
		return ret
	}
	return *o.Dob
}

// GetDobOk returns a tuple with the Dob field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Applicant) GetDobOk() (*string, bool) {
	if o == nil || o.Dob == nil {
		return nil, false
	}
	return o.Dob, true
}

// HasDob returns a boolean if a field has been set.
func (o *Applicant) HasDob() bool {
	if o != nil && o.Dob != nil {
		return true
	}

	return false
}

// SetDob gets a reference to the given string and assigns it to the Dob field.
func (o *Applicant) SetDob(v string) {
	o.Dob = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *Applicant) GetAddress() Address {
	if o == nil || o.Address == nil {
		var ret Address
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Applicant) GetAddressOk() (*Address, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *Applicant) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given Address and assigns it to the Address field.
func (o *Applicant) SetAddress(v Address) {
	o.Address = &v
}

// GetIdNumbers returns the IdNumbers field value if set, zero value otherwise.
func (o *Applicant) GetIdNumbers() []IdNumber {
	if o == nil || o.IdNumbers == nil {
		var ret []IdNumber
		return ret
	}
	return *o.IdNumbers
}

// GetIdNumbersOk returns a tuple with the IdNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Applicant) GetIdNumbersOk() (*[]IdNumber, bool) {
	if o == nil || o.IdNumbers == nil {
		return nil, false
	}
	return o.IdNumbers, true
}

// HasIdNumbers returns a boolean if a field has been set.
func (o *Applicant) HasIdNumbers() bool {
	if o != nil && o.IdNumbers != nil {
		return true
	}

	return false
}

// SetIdNumbers gets a reference to the given []IdNumber and assigns it to the IdNumbers field.
func (o *Applicant) SetIdNumbers(v []IdNumber) {
	o.IdNumbers = &v
}

func (o Applicant) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.DeleteAt != nil {
		toSerialize["delete_at"] = o.DeleteAt
	}
	if o.Href != nil {
		toSerialize["href"] = o.Href
	}
	if o.Sandbox != nil {
		toSerialize["sandbox"] = o.Sandbox
	}
	if o.FirstName != nil {
		toSerialize["first_name"] = o.FirstName
	}
	if o.LastName != nil {
		toSerialize["last_name"] = o.LastName
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.Dob != nil {
		toSerialize["dob"] = o.Dob
	}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	if o.IdNumbers != nil {
		toSerialize["id_numbers"] = o.IdNumbers
	}
	return json.Marshal(toSerialize)
}

type NullableApplicant struct {
	value *Applicant
	isSet bool
}

func (v NullableApplicant) Get() *Applicant {
	return v.value
}

func (v *NullableApplicant) Set(val *Applicant) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicant) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicant(val *Applicant) *NullableApplicant {
	return &NullableApplicant{value: val, isSet: true}
}

func (v NullableApplicant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


