/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
	"time"
)

// Check struct for Check
type Check struct {
	// The unique identifier for the check. Read-only.
	Id *string `json:"id,omitempty"`
	// The date and time when this check was created. Read-only.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The uri of this resource. Read-only.
	Href *string `json:"href,omitempty"`
	// The current state of the check in the checking process. Read-only.
	Status *string `json:"status,omitempty"`
	// The overall result of the check, based on the results of the constituent reports. Read-only.
	Result *string `json:"result,omitempty"`
	// A link to a PDF output of the check results. Append `.pdf` to get the pdf file. Read-only.
	DownloadUri *string `json:"download_uri,omitempty"`
	// A link to the applicant form, if `applicant_provides_data` is `true`. Read-only.
	FormUri *string `json:"form_uri,omitempty"`
	// For checks where `applicant_provides_data` is `true`, redirect to this URI when the applicant has submitted their data. Read-only.
	RedirectUri *string `json:"redirect_uri,omitempty"`
	// A link to the corresponding results page on the Onfido dashboard.
	ResultsUri *string `json:"results_uri,omitempty"`
	// An array of report names (strings).
	ReportNames *[]string `json:"report_names,omitempty"`
	// The ID of the applicant to do the check on.
	ApplicantId *string `json:"applicant_id,omitempty"`
	// Indicates whether the privacy notices and terms of service have been read and, where specific laws require, that consent has been given for Onfido.
	PrivacyNoticesReadConsentGiven *bool `json:"privacy_notices_read_consent_given,omitempty"`
	// Array of tags being assigned to this check.
	Tags *[]string `json:"tags,omitempty"`
	// Send an applicant form to applicant to complete to proceed with check. Defaults to false. 
	ApplicantProvidesData *bool `json:"applicant_provides_data,omitempty"`
	// For checks where `applicant_provides_data` is `true`, applicant form will not be automatically sent if `suppress_form_emails` is set to `true`. You can manually send the form at any time after the check has been created, using the link found in the form_uri attribute of the check object. Write-only. Defaults to false. 
	SuppressFormEmails *bool `json:"suppress_form_emails,omitempty"`
	// Defaults to `true`. Write-only. If set to `false`, you will only receive a response when all reports in your check have completed. 
	Asynchronous *bool `json:"asynchronous,omitempty"`
	// Optional. An array of strings describing which webhooks to trigger for this check. By default, all webhooks registered in the account will be triggered and this value will be null in the responses.
	WebhookIds *[]string `json:"webhook_ids,omitempty"`
	// An array of report ids.
	ReportIds *[]string `json:"report_ids,omitempty"`
	// Optional. An array of document ids, for use with Document reports only. If omitted, the Document report will use the most recently uploaded document by default.
	DocumentIds *[]string `json:"document_ids,omitempty"`
	// Returns a pre-determined consider sub-result in sandbox for the specific reports in the consider array.
	Consider *[]string `json:"consider,omitempty"`
	// Triggers a pre-determined sub-result response for sandbox Document reports.
	SubResult *string `json:"sub_result,omitempty"`
}

// NewCheck instantiates a new Check object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheck() *Check {
	this := Check{}
	return &this
}

// NewCheckWithDefaults instantiates a new Check object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckWithDefaults() *Check {
	this := Check{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Check) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Check) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Check) SetId(v string) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Check) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Check) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Check) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *Check) GetHref() string {
	if o == nil || o.Href == nil {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetHrefOk() (*string, bool) {
	if o == nil || o.Href == nil {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *Check) HasHref() bool {
	if o != nil && o.Href != nil {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *Check) SetHref(v string) {
	o.Href = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Check) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Check) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Check) SetStatus(v string) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *Check) GetResult() string {
	if o == nil || o.Result == nil {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetResultOk() (*string, bool) {
	if o == nil || o.Result == nil {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *Check) HasResult() bool {
	if o != nil && o.Result != nil {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *Check) SetResult(v string) {
	o.Result = &v
}

// GetDownloadUri returns the DownloadUri field value if set, zero value otherwise.
func (o *Check) GetDownloadUri() string {
	if o == nil || o.DownloadUri == nil {
		var ret string
		return ret
	}
	return *o.DownloadUri
}

// GetDownloadUriOk returns a tuple with the DownloadUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetDownloadUriOk() (*string, bool) {
	if o == nil || o.DownloadUri == nil {
		return nil, false
	}
	return o.DownloadUri, true
}

// HasDownloadUri returns a boolean if a field has been set.
func (o *Check) HasDownloadUri() bool {
	if o != nil && o.DownloadUri != nil {
		return true
	}

	return false
}

// SetDownloadUri gets a reference to the given string and assigns it to the DownloadUri field.
func (o *Check) SetDownloadUri(v string) {
	o.DownloadUri = &v
}

// GetFormUri returns the FormUri field value if set, zero value otherwise.
func (o *Check) GetFormUri() string {
	if o == nil || o.FormUri == nil {
		var ret string
		return ret
	}
	return *o.FormUri
}

// GetFormUriOk returns a tuple with the FormUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetFormUriOk() (*string, bool) {
	if o == nil || o.FormUri == nil {
		return nil, false
	}
	return o.FormUri, true
}

// HasFormUri returns a boolean if a field has been set.
func (o *Check) HasFormUri() bool {
	if o != nil && o.FormUri != nil {
		return true
	}

	return false
}

// SetFormUri gets a reference to the given string and assigns it to the FormUri field.
func (o *Check) SetFormUri(v string) {
	o.FormUri = &v
}

// GetRedirectUri returns the RedirectUri field value if set, zero value otherwise.
func (o *Check) GetRedirectUri() string {
	if o == nil || o.RedirectUri == nil {
		var ret string
		return ret
	}
	return *o.RedirectUri
}

// GetRedirectUriOk returns a tuple with the RedirectUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetRedirectUriOk() (*string, bool) {
	if o == nil || o.RedirectUri == nil {
		return nil, false
	}
	return o.RedirectUri, true
}

// HasRedirectUri returns a boolean if a field has been set.
func (o *Check) HasRedirectUri() bool {
	if o != nil && o.RedirectUri != nil {
		return true
	}

	return false
}

// SetRedirectUri gets a reference to the given string and assigns it to the RedirectUri field.
func (o *Check) SetRedirectUri(v string) {
	o.RedirectUri = &v
}

// GetResultsUri returns the ResultsUri field value if set, zero value otherwise.
func (o *Check) GetResultsUri() string {
	if o == nil || o.ResultsUri == nil {
		var ret string
		return ret
	}
	return *o.ResultsUri
}

// GetResultsUriOk returns a tuple with the ResultsUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetResultsUriOk() (*string, bool) {
	if o == nil || o.ResultsUri == nil {
		return nil, false
	}
	return o.ResultsUri, true
}

// HasResultsUri returns a boolean if a field has been set.
func (o *Check) HasResultsUri() bool {
	if o != nil && o.ResultsUri != nil {
		return true
	}

	return false
}

// SetResultsUri gets a reference to the given string and assigns it to the ResultsUri field.
func (o *Check) SetResultsUri(v string) {
	o.ResultsUri = &v
}

// GetReportNames returns the ReportNames field value if set, zero value otherwise.
func (o *Check) GetReportNames() []string {
	if o == nil || o.ReportNames == nil {
		var ret []string
		return ret
	}
	return *o.ReportNames
}

// GetReportNamesOk returns a tuple with the ReportNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetReportNamesOk() (*[]string, bool) {
	if o == nil || o.ReportNames == nil {
		return nil, false
	}
	return o.ReportNames, true
}

// HasReportNames returns a boolean if a field has been set.
func (o *Check) HasReportNames() bool {
	if o != nil && o.ReportNames != nil {
		return true
	}

	return false
}

// SetReportNames gets a reference to the given []string and assigns it to the ReportNames field.
func (o *Check) SetReportNames(v []string) {
	o.ReportNames = &v
}

// GetApplicantId returns the ApplicantId field value if set, zero value otherwise.
func (o *Check) GetApplicantId() string {
	if o == nil || o.ApplicantId == nil {
		var ret string
		return ret
	}
	return *o.ApplicantId
}

// GetApplicantIdOk returns a tuple with the ApplicantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetApplicantIdOk() (*string, bool) {
	if o == nil || o.ApplicantId == nil {
		return nil, false
	}
	return o.ApplicantId, true
}

// HasApplicantId returns a boolean if a field has been set.
func (o *Check) HasApplicantId() bool {
	if o != nil && o.ApplicantId != nil {
		return true
	}

	return false
}

// SetApplicantId gets a reference to the given string and assigns it to the ApplicantId field.
func (o *Check) SetApplicantId(v string) {
	o.ApplicantId = &v
}

// GetPrivacyNoticesReadConsentGiven returns the PrivacyNoticesReadConsentGiven field value if set, zero value otherwise.
func (o *Check) GetPrivacyNoticesReadConsentGiven() bool {
	if o == nil || o.PrivacyNoticesReadConsentGiven == nil {
		var ret bool
		return ret
	}
	return *o.PrivacyNoticesReadConsentGiven
}

// GetPrivacyNoticesReadConsentGivenOk returns a tuple with the PrivacyNoticesReadConsentGiven field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetPrivacyNoticesReadConsentGivenOk() (*bool, bool) {
	if o == nil || o.PrivacyNoticesReadConsentGiven == nil {
		return nil, false
	}
	return o.PrivacyNoticesReadConsentGiven, true
}

// HasPrivacyNoticesReadConsentGiven returns a boolean if a field has been set.
func (o *Check) HasPrivacyNoticesReadConsentGiven() bool {
	if o != nil && o.PrivacyNoticesReadConsentGiven != nil {
		return true
	}

	return false
}

// SetPrivacyNoticesReadConsentGiven gets a reference to the given bool and assigns it to the PrivacyNoticesReadConsentGiven field.
func (o *Check) SetPrivacyNoticesReadConsentGiven(v bool) {
	o.PrivacyNoticesReadConsentGiven = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Check) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetTagsOk() (*[]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Check) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *Check) SetTags(v []string) {
	o.Tags = &v
}

// GetApplicantProvidesData returns the ApplicantProvidesData field value if set, zero value otherwise.
func (o *Check) GetApplicantProvidesData() bool {
	if o == nil || o.ApplicantProvidesData == nil {
		var ret bool
		return ret
	}
	return *o.ApplicantProvidesData
}

// GetApplicantProvidesDataOk returns a tuple with the ApplicantProvidesData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetApplicantProvidesDataOk() (*bool, bool) {
	if o == nil || o.ApplicantProvidesData == nil {
		return nil, false
	}
	return o.ApplicantProvidesData, true
}

// HasApplicantProvidesData returns a boolean if a field has been set.
func (o *Check) HasApplicantProvidesData() bool {
	if o != nil && o.ApplicantProvidesData != nil {
		return true
	}

	return false
}

// SetApplicantProvidesData gets a reference to the given bool and assigns it to the ApplicantProvidesData field.
func (o *Check) SetApplicantProvidesData(v bool) {
	o.ApplicantProvidesData = &v
}

// GetSuppressFormEmails returns the SuppressFormEmails field value if set, zero value otherwise.
func (o *Check) GetSuppressFormEmails() bool {
	if o == nil || o.SuppressFormEmails == nil {
		var ret bool
		return ret
	}
	return *o.SuppressFormEmails
}

// GetSuppressFormEmailsOk returns a tuple with the SuppressFormEmails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetSuppressFormEmailsOk() (*bool, bool) {
	if o == nil || o.SuppressFormEmails == nil {
		return nil, false
	}
	return o.SuppressFormEmails, true
}

// HasSuppressFormEmails returns a boolean if a field has been set.
func (o *Check) HasSuppressFormEmails() bool {
	if o != nil && o.SuppressFormEmails != nil {
		return true
	}

	return false
}

// SetSuppressFormEmails gets a reference to the given bool and assigns it to the SuppressFormEmails field.
func (o *Check) SetSuppressFormEmails(v bool) {
	o.SuppressFormEmails = &v
}

// GetAsynchronous returns the Asynchronous field value if set, zero value otherwise.
func (o *Check) GetAsynchronous() bool {
	if o == nil || o.Asynchronous == nil {
		var ret bool
		return ret
	}
	return *o.Asynchronous
}

// GetAsynchronousOk returns a tuple with the Asynchronous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetAsynchronousOk() (*bool, bool) {
	if o == nil || o.Asynchronous == nil {
		return nil, false
	}
	return o.Asynchronous, true
}

// HasAsynchronous returns a boolean if a field has been set.
func (o *Check) HasAsynchronous() bool {
	if o != nil && o.Asynchronous != nil {
		return true
	}

	return false
}

// SetAsynchronous gets a reference to the given bool and assigns it to the Asynchronous field.
func (o *Check) SetAsynchronous(v bool) {
	o.Asynchronous = &v
}

// GetWebhookIds returns the WebhookIds field value if set, zero value otherwise.
func (o *Check) GetWebhookIds() []string {
	if o == nil || o.WebhookIds == nil {
		var ret []string
		return ret
	}
	return *o.WebhookIds
}

// GetWebhookIdsOk returns a tuple with the WebhookIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetWebhookIdsOk() (*[]string, bool) {
	if o == nil || o.WebhookIds == nil {
		return nil, false
	}
	return o.WebhookIds, true
}

// HasWebhookIds returns a boolean if a field has been set.
func (o *Check) HasWebhookIds() bool {
	if o != nil && o.WebhookIds != nil {
		return true
	}

	return false
}

// SetWebhookIds gets a reference to the given []string and assigns it to the WebhookIds field.
func (o *Check) SetWebhookIds(v []string) {
	o.WebhookIds = &v
}

// GetReportIds returns the ReportIds field value if set, zero value otherwise.
func (o *Check) GetReportIds() []string {
	if o == nil || o.ReportIds == nil {
		var ret []string
		return ret
	}
	return *o.ReportIds
}

// GetReportIdsOk returns a tuple with the ReportIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetReportIdsOk() (*[]string, bool) {
	if o == nil || o.ReportIds == nil {
		return nil, false
	}
	return o.ReportIds, true
}

// HasReportIds returns a boolean if a field has been set.
func (o *Check) HasReportIds() bool {
	if o != nil && o.ReportIds != nil {
		return true
	}

	return false
}

// SetReportIds gets a reference to the given []string and assigns it to the ReportIds field.
func (o *Check) SetReportIds(v []string) {
	o.ReportIds = &v
}

// GetDocumentIds returns the DocumentIds field value if set, zero value otherwise.
func (o *Check) GetDocumentIds() []string {
	if o == nil || o.DocumentIds == nil {
		var ret []string
		return ret
	}
	return *o.DocumentIds
}

// GetDocumentIdsOk returns a tuple with the DocumentIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetDocumentIdsOk() (*[]string, bool) {
	if o == nil || o.DocumentIds == nil {
		return nil, false
	}
	return o.DocumentIds, true
}

// HasDocumentIds returns a boolean if a field has been set.
func (o *Check) HasDocumentIds() bool {
	if o != nil && o.DocumentIds != nil {
		return true
	}

	return false
}

// SetDocumentIds gets a reference to the given []string and assigns it to the DocumentIds field.
func (o *Check) SetDocumentIds(v []string) {
	o.DocumentIds = &v
}

// GetConsider returns the Consider field value if set, zero value otherwise.
func (o *Check) GetConsider() []string {
	if o == nil || o.Consider == nil {
		var ret []string
		return ret
	}
	return *o.Consider
}

// GetConsiderOk returns a tuple with the Consider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetConsiderOk() (*[]string, bool) {
	if o == nil || o.Consider == nil {
		return nil, false
	}
	return o.Consider, true
}

// HasConsider returns a boolean if a field has been set.
func (o *Check) HasConsider() bool {
	if o != nil && o.Consider != nil {
		return true
	}

	return false
}

// SetConsider gets a reference to the given []string and assigns it to the Consider field.
func (o *Check) SetConsider(v []string) {
	o.Consider = &v
}

// GetSubResult returns the SubResult field value if set, zero value otherwise.
func (o *Check) GetSubResult() string {
	if o == nil || o.SubResult == nil {
		var ret string
		return ret
	}
	return *o.SubResult
}

// GetSubResultOk returns a tuple with the SubResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Check) GetSubResultOk() (*string, bool) {
	if o == nil || o.SubResult == nil {
		return nil, false
	}
	return o.SubResult, true
}

// HasSubResult returns a boolean if a field has been set.
func (o *Check) HasSubResult() bool {
	if o != nil && o.SubResult != nil {
		return true
	}

	return false
}

// SetSubResult gets a reference to the given string and assigns it to the SubResult field.
func (o *Check) SetSubResult(v string) {
	o.SubResult = &v
}

func (o Check) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.Href != nil {
		toSerialize["href"] = o.Href
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	if o.DownloadUri != nil {
		toSerialize["download_uri"] = o.DownloadUri
	}
	if o.FormUri != nil {
		toSerialize["form_uri"] = o.FormUri
	}
	if o.RedirectUri != nil {
		toSerialize["redirect_uri"] = o.RedirectUri
	}
	if o.ResultsUri != nil {
		toSerialize["results_uri"] = o.ResultsUri
	}
	if o.ReportNames != nil {
		toSerialize["report_names"] = o.ReportNames
	}
	if o.ApplicantId != nil {
		toSerialize["applicant_id"] = o.ApplicantId
	}
	if o.PrivacyNoticesReadConsentGiven != nil {
		toSerialize["privacy_notices_read_consent_given"] = o.PrivacyNoticesReadConsentGiven
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.ApplicantProvidesData != nil {
		toSerialize["applicant_provides_data"] = o.ApplicantProvidesData
	}
	if o.SuppressFormEmails != nil {
		toSerialize["suppress_form_emails"] = o.SuppressFormEmails
	}
	if o.Asynchronous != nil {
		toSerialize["asynchronous"] = o.Asynchronous
	}
	if o.WebhookIds != nil {
		toSerialize["webhook_ids"] = o.WebhookIds
	}
	if o.ReportIds != nil {
		toSerialize["report_ids"] = o.ReportIds
	}
	if o.DocumentIds != nil {
		toSerialize["document_ids"] = o.DocumentIds
	}
	if o.Consider != nil {
		toSerialize["consider"] = o.Consider
	}
	if o.SubResult != nil {
		toSerialize["sub_result"] = o.SubResult
	}
	return json.Marshal(toSerialize)
}

type NullableCheck struct {
	value *Check
	isSet bool
}

func (v NullableCheck) Get() *Check {
	return v.value
}

func (v *NullableCheck) Set(val *Check) {
	v.value = val
	v.isSet = true
}

func (v NullableCheck) IsSet() bool {
	return v.isSet
}

func (v *NullableCheck) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheck(val *Check) *NullableCheck {
	return &NullableCheck{value: val, isSet: true}
}

func (v NullableCheck) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheck) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


