/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// ReportDocument struct for ReportDocument
type ReportDocument struct {
	// ID of uploaded document to use.
	Id string `json:"id"`
}

// NewReportDocument instantiates a new ReportDocument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportDocument(id string) *ReportDocument {
	this := ReportDocument{}
	this.Id = id
	return &this
}

// NewReportDocumentWithDefaults instantiates a new ReportDocument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportDocumentWithDefaults() *ReportDocument {
	this := ReportDocument{}
	return &this
}

// GetId returns the Id field value
func (o *ReportDocument) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ReportDocument) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ReportDocument) SetId(v string) {
	o.Id = v
}

func (o ReportDocument) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableReportDocument struct {
	value *ReportDocument
	isSet bool
}

func (v NullableReportDocument) Get() *ReportDocument {
	return v.value
}

func (v *NullableReportDocument) Set(val *ReportDocument) {
	v.value = val
	v.isSet = true
}

func (v NullableReportDocument) IsSet() bool {
	return v.isSet
}

func (v *NullableReportDocument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportDocument(val *ReportDocument) *NullableReportDocument {
	return &NullableReportDocument{value: val, isSet: true}
}

func (v NullableReportDocument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportDocument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


